name: Build & Deploy Spring app

on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and Deploy Spring boot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        users: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'

      - name: Unit Tests
        run: gradle -B test --build.gradle.kts